### ISSUE TITLE
Bump Minreq

### ISSUE THREAD

**Issue by darosior** [darosior/ledger_installer#2]
A new version with my fix was released: https://github.com/neonmoe/minreq/releases/tag/2.11.1

**Comment by pythcoiner** [comment]
it looks to me this have been done in [5151cfd](https://github.com/darosior/ledger_installer/commit/5151cfd0890808c19a0c1a448230389a2b05f37a):

https://github.com/darosior/ledger_installer/blob/9009dc0c1b84f1657ac27e061a096708fdab646d/ledger_manager/Cargo.toml#L17C1-L17C72
